# Generated by Django 4.2.1 on 2023-05-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField(blank=True, null=True)),
                ('url', models.TextField()),
                ('source', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
